# Data Generation Configuration
# =============================

# Grid World Settings
grid_size: 10  # Inner navigable area (10×10)
wall_padding: 1  # Wall border around navigable area
obstacle_density_range: [0.1, 0.4]  # Min and max obstacle density
min_path_length: 5
max_path_length: 50

# Generation Settings
num_environments: 1000
max_generation_attempts: 100

# Perception Settings
<<<<<<< Updated upstream
<<<<<<< Updated upstream
perception_size: 3  # Perception window size (3 for 3×3, 5 for 5×5)
=======
perception_size: 3  # Perception window size (3×3 only for original solution)
use_goal_delta: true  # Include goal relative coordinates (dx, dy)
>>>>>>> Stashed changes
=======
perception_size: 3  # Perception window size (3×3 only for original solution)
use_goal_delta: true  # Include goal relative coordinates (dx, dy)
>>>>>>> Stashed changes

# Dataset Sizes
small_dataset:
  num_environments: 100
  obstacle_density_range: [0.1, 0.3]
  max_path_length: 25

medium_dataset:
  num_environments: 500
  obstacle_density_range: [0.1, 0.35]
  max_path_length: 30

large_dataset:
  num_environments: 1000
  obstacle_density_range: [0.1, 0.4]
  max_path_length: 50

# Output Settings
output_directory: "data/"
save_format: "npz"
include_metadata: true
