# Neural Network Model Configuration
# ==================================

# Model Architecture
input_size: 9  # 3x3 perception flattened
hidden_sizes: [64, 32]  # Hidden layer sizes
output_size: 4  # 4 actions: UP, DOWN, LEFT, RIGHT
activation: "relu"
dropout_rate: 0.2

# Training Parameters
learning_rate: 0.001
batch_size: 32
num_epochs: 100
optimizer: "adam"
loss_function: "cross_entropy"

# Data Processing
train_split: 0.8
validation_split: 0.1
test_split: 0.1
shuffle_data: true
random_seed: 42

# Early Stopping
early_stopping:
  enabled: true
  patience: 10
  monitor: "validation_loss"
  mode: "min"

# Model Checkpointing
checkpointing:
  enabled: true
  save_best_only: true
  monitor: "validation_accuracy"
  mode: "max"
  save_dir: "models/checkpoints/"

# Evaluation Metrics
metrics:
  - "accuracy"
  - "precision"
  - "recall"
  - "f1_score"
  - "confusion_matrix"
